---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: grafana
spec:
  hosts:
    - "grafana.{{ .Values.domain }}"
  gateways:
    - grafana 
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "grafana"
            port:
              number: 80