global:
  grafana:
    enabled: false
    proxy: false

  prometheus:
    enabled: false
  
  savedReports:
    enabled: true
  
  cloudCostReports:
    enabled: true

  amp:
    enabled: true
    prometheusServerEndpoint: http://localhost:8005/workspaces/${WORKSPACE_ID}
    remoteWriteService: https://aps-workspaces.${REGION}.amazonaws.com/workspaces/${WORKSPACE_ID}/api/v1/remote_write
    sigv4:
      region: ${REGION}

sigV4Proxy:
  region: ${REGION}
  host: aps-workspaces.${REGION}.amazonaws.com

kubecostProductConfigs:
  clusterName: "${EKS_CLUSTER_NAME}"

prometheus:
  server:
    global:
      external_labels:
        cluster_id: ${EKS_CLUSTER_NAME}
  nodeExporter:
    enabled: false
  kube-state-metrics:
    disabled: true

networkCosts:
  enabled: true

pricingCsv:
  enabled: false
  location:
    provider: "AWS"
    region: "us-east-1"
    URI: s3://kc-csv-test/pricing_schema.csv  # a valid file URI
    csvAccessCredentials: pricing-schema-access-secret

kubecostToken: "aGFyc2hpdC5rdW1hckBzb3VyY2VmdXNlLmNvbQ==xm343yadf98"